### PR TITLE
Use node v18

### PR DESCRIPTION
**Pull request by dhogan8**

### CODE REVIEW

**Review by kevcenteno — CHANGES_REQUESTED** [review]
https://github.com/maxmind-zendesk-theme/zendesk-theme/blob/main/.github/workflows/build-test.yml needs to be updated as well

**Review by oalders — APPROVED** [review]
It looks like the lockfile was re-formatted, but doesn't have any actually differences. Do you know why that is?

**Comment by dhogan8** [comment]
@oalders I'm not actually sure. For some reason each time I run `npm i`, the lockfile gets updated locally.

**Comment by kevcenteno** [comment]
@dhogan8 @oalders It's because we were running `npx npm-force-resolutions`.  This was useful when we had pinned sub-dependency resolutions in our package.json, but this is no longer the case.  See: https://github.com/maxmind-zendesk-theme/zendesk-theme/commit/3c87e875f6885491c9d487ed5bac8b7356be0863#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R17

I've removed it in an upcoming PR.

**Review by kevcenteno — APPROVED** [review]

**Review by oalders — APPROVED** [review]
```text
╔═══════════════════════════════════════╤═════════════╤═════════════╗
║ package-lock.json                     │             │             ║
╟───────────────────────────────────────┼─────────────┼─────────────╢
║ package                               │ old version │ new version ║
╟───────────────────────────────────────┼─────────────┼─────────────╢
║ node_modules/meow/node_modules/semver │ 7.3.7       │ 7.5.4       ║
╚═══════════════════════════════════════╧═════════════╧═════════════╝
```

**Pull request merged**
